[package]
name = "rust_playground"
version = "0.1.0"
authors = ["stani"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.114"
serde_json = "1.0.56"
serde_derive = "1.0.114"
rand = "0.6.5"